node:
  image: opendigitaleducation/node:12-alpine
  working_dir: /home/node/app
  net: host
  volumes:
    - ./:/home/node/app
    - ~/.npm:/.npm
    - ../entcore:/home/node/entcore
    - ../crm:/home/node/crm
  environment:
    - NG_CLI_ANALYTICS=false
