services:
  node:
    image: node:lts-gallium
    working_dir: /home/node/app
    volumes:
    - ./:/home/node/app
    - ~/.npm:/.npm
    - ../entcore:/home/node/entcore
    environment:
    - NG_CLI_ANALYTICS=false
